apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmic-whale
  namespace: star-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmic-whale
  template:
    metadata:
      labels:
        app: cosmic-whale
    spec:
      securityContext:
        runAsUser: 20000  # Pod-level security context
      containers:
      - name: cosmic-whale
        image: notmiddev30/cosmic-whale-new:0.1
        securityContext:
          allowPrivilegeEscalation: false  # Container-level security context
