apiVersion: batch/v1
kind: CronJob
metadata:
  name: pi
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pi
            image: notmiddev30/pi:0.1
            command: ["go", "run", "pi.go"]
          restartPolicy: Never
      backoffLimit: 0
      activeDeadlineSeconds: 10
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 5
