apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-listing-binding
  namespace: non-critical-systems
subjects:
- kind: ServiceAccount
  name: hyper-v-sa
  namespace: non-critical-systems
roleRef:
  kind: Role
  name: pod-listing
  apiGroup: rbac.authorization.k8s.io
