apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"starblaze-app"},"name":"starblaze-deployment","namespace":"starblaze"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"starblaze-app"}},"template":{"metadata":{"labels":{"app":"starblaze-app"}},"spec":{"containers":[{"image":"nginx:1.14.2","name":"starblaze-container","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2024-04-21T20:00:43Z"
  generation: 2
  labels:
    app: starblaze-app
    star: thousand
  name: starblaze-deployment
  namespace: starblaze
  resourceVersion: "11274"
  uid: bcc56d41-ebf8-4cc8-8f73-b18f0be8b3c2
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: starblaze-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: starblaze-app
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: starblaze-container
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2024-04-21T20:00:43Z"
    lastUpdateTime: "2024-04-21T20:01:06Z"
    message: ReplicaSet "starblaze-deployment-74f54658df" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-04-21T21:20:35Z"
    lastUpdateTime: "2024-04-21T21:20:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
